import { createClient } from '@supabase/supabase-js';

const supabaseUrl = typeof process !== 'undefined' && process.env.VITE_SUPABASE_URL 
  ? process.env.VITE_SUPABASE_URL 
  : import.meta.env?.VITE_SUPABASE_URL;
const supabaseAnonKey = typeof process !== 'undefined' && process.env.VITE_SUPABASE_ANON_KEY 
  ? process.env.VITE_SUPABASE_ANON_KEY 
  : import.meta.env?.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types
export interface Database {
  public: {
    Tables: {
      surveys: {
        Row: {
          id: string;
          survey_name: string;
          state: string;
          district: string;
          quarter: string;
          total_records: number;
          records_submitted: number;
          records_under_supervisor_review: number;
          records_under_ds_review: number;
          records_approved: number;
          records_rejected: number;
          records_pending_correction: number;
          submission_date: string;
          last_updated: string;
          fsu_count: number;
          household_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          survey_name: string;
          state: string;
          district: string;
          quarter: string;
          total_records?: number;
          records_submitted?: number;
          records_under_supervisor_review?: number;
          records_under_ds_review?: number;
          records_approved?: number;
          records_rejected?: number;
          records_pending_correction?: number;
          submission_date?: string;
          last_updated?: string;
          fsu_count?: number;
          household_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          survey_name?: string;
          state?: string;
          district?: string;
          quarter?: string;
          total_records?: number;
          records_submitted?: number;
          records_under_supervisor_review?: number;
          records_under_ds_review?: number;
          records_approved?: number;
          records_rejected?: number;
          records_pending_correction?: number;
          submission_date?: string;
          last_updated?: string;
          fsu_count?: number;
          household_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      fsus: {
        Row: {
          id: string;
          fsu_code: string;
          fsu_name: string;
          survey_id: string;
          survey_name: string;
          state: string;
          district: string;
          block: string;
          village: string;
          quarter: string;
          enumerator_id: string;
          enumerator_name: string;
          supervisor_id: string;
          supervisor_name: string;
          ds_id: string;
          ds_name: string;
          total_households: number;
          households_submitted: number;
          households_approved: number;
          households_rejected: number;
          households_pending_correction: number;
          households_under_supervisor_review: number;
          households_under_ds_review: number;
          data_quality_score: number;
          completeness_score: number;
          consistency_score: number;
          submission_date: string;
          last_updated: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          fsu_code: string;
          fsu_name: string;
          survey_id: string;
          survey_name: string;
          state: string;
          district: string;
          block: string;
          village: string;
          quarter: string;
          enumerator_id: string;
          enumerator_name: string;
          supervisor_id: string;
          supervisor_name: string;
          ds_id: string;
          ds_name: string;
          total_households?: number;
          households_submitted?: number;
          households_approved?: number;
          households_rejected?: number;
          households_pending_correction?: number;
          households_under_supervisor_review?: number;
          households_under_ds_review?: number;
          data_quality_score?: number;
          completeness_score?: number;
          consistency_score?: number;
          submission_date?: string;
          last_updated?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          fsu_code?: string;
          fsu_name?: string;
          survey_id?: string;
          survey_name?: string;
          state?: string;
          district?: string;
          block?: string;
          village?: string;
          quarter?: string;
          enumerator_id?: string;
          enumerator_name?: string;
          supervisor_id?: string;
          supervisor_name?: string;
          ds_id?: string;
          ds_name?: string;
          total_households?: number;
          households_submitted?: number;
          households_approved?: number;
          households_rejected?: number;
          households_pending_correction?: number;
          households_under_supervisor_review?: number;
          households_under_ds_review?: number;
          data_quality_score?: number;
          completeness_score?: number;
          consistency_score?: number;
          submission_date?: string;
          last_updated?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      households: {
        Row: {
          id: string;
          household_id: string;
          fsu_id: string;
          fsu_code: string;
          survey_name: string;
          state: string;
          district: string;
          quarter: string;
          head_of_household: string;
          household_size: number;
          enumerator_id: string;
          enumerator_name: string;
          submission_date: string;
          supervisor_review_date: string | null;
          ds_review_date: string | null;
          current_status: string;
          supervisor_comments: string | null;
          ds_comments: string | null;
          data_quality_score: number;
          completeness_percentage: number;
          critical_errors: number;
          minor_errors: number;
          scrutiny_iterations: number;
          original_data: any;
          revised_data: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          fsu_id: string;
          fsu_code: string;
          survey_name: string;
          state: string;
          district: string;
          quarter: string;
          head_of_household: string;
          household_size?: number;
          enumerator_id: string;
          enumerator_name: string;
          submission_date?: string;
          supervisor_review_date?: string | null;
          ds_review_date?: string | null;
          current_status?: string;
          supervisor_comments?: string | null;
          ds_comments?: string | null;
          data_quality_score?: number;
          completeness_percentage?: number;
          critical_errors?: number;
          minor_errors?: number;
          scrutiny_iterations?: number;
          original_data?: any;
          revised_data?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          fsu_id?: string;
          fsu_code?: string;
          survey_name?: string;
          state?: string;
          district?: string;
          quarter?: string;
          head_of_household?: string;
          household_size?: number;
          enumerator_id?: string;
          enumerator_name?: string;
          submission_date?: string;
          supervisor_review_date?: string | null;
          ds_review_date?: string | null;
          current_status?: string;
          supervisor_comments?: string | null;
          ds_comments?: string | null;
          data_quality_score?: number;
          completeness_percentage?: number;
          critical_errors?: number;
          minor_errors?: number;
          scrutiny_iterations?: number;
          original_data?: any;
          revised_data?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      scrutiny_changes: {
        Row: {
          id: string;
          household_id: string;
          survey_id: string | null;
          schedule: string | null;
          block: string | null;
          field_name: string;
          field_label: string;
          original_value: string | null;
          revised_value: string | null;
          change_type: string;
          change_reason: string;
          changed_by: string;
          change_date: string;
          severity: string;
          impact: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          survey_id?: string | null;
          schedule?: string | null;
          block?: string | null;
          field_name: string;
          field_label: string;
          original_value?: string | null;
          revised_value?: string | null;
          change_type?: string;
          change_reason: string;
          changed_by?: string;
          change_date?: string;
          severity?: string;
          impact?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          survey_id?: string | null;
          schedule?: string | null;
          block?: string | null;
          field_name?: string;
          field_label?: string;
          original_value?: string | null;
          revised_value?: string | null;
          change_type?: string;
          change_reason?: string;
          changed_by?: string;
          change_date?: string;
          severity?: string;
          impact?: string;
          created_at?: string;
        };
      };
      supervisor_performance: {
        Row: {
          id: string;
          supervisor_name: string;
          supervisor_id: string;
          state: string;
          district: string;
          total_assigned: number;
          total_reviewed: number;
          total_approved: number;
          total_rejected: number;
          avg_review_time: number;
          quality_score: number;
          pending_reviews: number;
          last_active: string;
          fsus_covered: number;
          households_reviewed: number;
          critical_errors_found: number;
          data_changes_initiated: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supervisor_name: string;
          supervisor_id: string;
          state: string;
          district: string;
          total_assigned?: number;
          total_reviewed?: number;
          total_approved?: number;
          total_rejected?: number;
          avg_review_time?: number;
          quality_score?: number;
          pending_reviews?: number;
          last_active?: string;
          fsus_covered?: number;
          households_reviewed?: number;
          critical_errors_found?: number;
          data_changes_initiated?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supervisor_name?: string;
          supervisor_id?: string;
          state?: string;
          district?: string;
          total_assigned?: number;
          total_reviewed?: number;
          total_approved?: number;
          total_rejected?: number;
          avg_review_time?: number;
          quality_score?: number;
          pending_reviews?: number;
          last_active?: string;
          fsus_covered?: number;
          households_reviewed?: number;
          critical_errors_found?: number;
          data_changes_initiated?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      ds_performance: {
        Row: {
          id: string;
          ds_name: string;
          ds_id: string;
          state: string;
          total_assigned: number;
          total_reviewed: number;
          total_approved: number;
          total_rejected: number;
          total_sent_back: number;
          avg_review_time: number;
          quality_score: number;
          pending_reviews: number;
          last_active: string;
          fsus_covered: number;
          households_reviewed: number;
          critical_errors_found: number;
          data_changes_initiated: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ds_name: string;
          ds_id: string;
          state: string;
          total_assigned?: number;
          total_reviewed?: number;
          total_approved?: number;
          total_rejected?: number;
          total_sent_back?: number;
          avg_review_time?: number;
          quality_score?: number;
          pending_reviews?: number;
          last_active?: string;
          fsus_covered?: number;
          households_reviewed?: number;
          critical_errors_found?: number;
          data_changes_initiated?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ds_name?: string;
          ds_id?: string;
          state?: string;
          total_assigned?: number;
          total_reviewed?: number;
          total_approved?: number;
          total_rejected?: number;
          total_sent_back?: number;
          avg_review_time?: number;
          quality_score?: number;
          pending_reviews?: number;
          last_active?: string;
          fsus_covered?: number;
          households_reviewed?: number;
          critical_errors_found?: number;
          data_changes_initiated?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}